config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
  get 'top/index'
  end

  root "top#index"
  
  get "about" => "top#about", as: "about"
  get "login" => "top#login", as: "login"

  resources :users, only: [:index, :show] do
    resources :articles, only: [:index]
  end
  resources :articles do
    member { patch :like, :unlike, :comment }
    collection { get :voted, :commented }
    resources :comments
  end
  resource :session, only: [:create, :destroy]
  resource :account, only: [:show, :edit, :update]
  
  namespace :admin do
    root to: "top#index"
    resources :users
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  STATUS_VALUES = %w(draft member_only public)
  
  # 1ページあたりの取得件数
  paginates_per 5
  
  # 記事の作成ユーザーを"author"として紐付け
  belongs_to :author, class_name: "User", foreign_key: "user_id"
  
  # 記事への投票をユーザーと紐付け
  has_many :votes, dependent: :destroy
  has_many :voters, through: :votes, source: :user
  
  # 記事へのコメントをユーザーと紐付け
  has_many :comments, dependent: :destroy
  has_many :commenters, through: :comments, source: :user
  
  validates :title,
    presence: true,
    length: { maximum: 50 }
    
  #validates :description,
    #presence: true
    
  validates :status,
    inclusion: { in: STATUS_VALUES }
  
  # 全公開スコープ
  scope :common, -> { where(status: "public") }
  
  # 公開済みスコープ
  scope :published, -> { where("status <> ?", "draft") }
  
  # 全取得スコープ
  scope :full, ->(user) { where("status <> ? OR user_id = ?", "draft", user.id) }
  
  # アクセス可能スコープ
  scope :readable_for, ->(user) { user ? full(user) : common }
  
  class << self
    def status_text(status)
      I18n.t("activerecord.attributes.article.status_#{status}")
    end
    
    def status_options
      STATUS_VALUES.map { |status| [status_text(status), status] }
    end
    
    def sidebar_articles(user, num = 5)
      readable_for(user).order(released_at: :desc).limit(num)
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # 一覧と詳細以外はログイン必須
  before_action :login_required, except: [:index, :show]
  
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    if params[:user_id]
      @user = User.find(params[:user_id])
      @articles = @user.articles
    else
      @articles = Article.all
    end
    @articles = @articles.readable_for(current_user).order(released_at: :desc).page(params[:page])
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.readable_for(current_user).find(params[:id])
    @comments = Comment.find_by_sql(["SELECT comments.comment, comments.user_id, comments.created_at, users.full_name, user_images.content_type
                  FROM comments
                  INNER JOIN (users INNER JOIN user_images ON users.id = user_images.user_id ) ON comments.user_id = users.id
                  WHERE comments.article_id = ?
                  ORDER BY comments.created_at DESC", params[:id]])
  end

  # GET /articles/new
  def new
    @article = Article.new(released_at: Time.current)
  end

  # GET /articles/1/edit
  def edit
    @article = Article.readable_for(current_user).find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.author = current_user
    if @article.save
      redirect_to @article, notice: "記事を作成しました。"
    else
      render "new"
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    @article = Article.readable_for(current_user).find(params[:id])
    @article.assign_attributes(article_params)
    if @article.save
      redirect_to @article, notice: "記事を更新しました。"
    else
      render "edit"
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: '記事を削除しました。' }
      format.json { head :no_content }
    end
  end
  
  # コメント登録
  def comment
    
    #@comment.assign_attributes(comment_params)
    @comment = Comment.new
    @comment.comment = params[:comment]
    @comment.article_id = params[:id]
    @comment.user_id = session[:user_id]
    if @comment.save
      @article = Article.published.find(params[:id])
      redirect_to @article, notice: "コメントを登録しました。"
    else
      render "show"
    end
  end
  
  # 投票
  def like
    @article = Article.published.find(params[:id])
    current_user.voted_articles << @article
    redirect_to @article, notice: "投票しました。"
  end
  
  # 投票を削除
  def unlike
    current_user.voted_articles.destroy(Article.find(params[:id]))
    redirect_to Article.find(params[:id]), notice: "投票を削除しました。"
  end

  # 投票した記事一覧
  def voted
    @articles = current_user.voted_articles.published.order("votes.created_at DESC")
  end
  
  # コメントした記事一覧
  def commented
    @articles = current_user.commented_articles.published.order("comments.created_at DESC")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :description, :released_at, :status)
    end
    
    def comment_params
      params.require(:comment).permit(:comment)
    end
    
    def send_image
      if @comment.image.present?
        send_data @comment.image.data, type: @comment.image.content_type, disposition: "inline"
      else
        raise NotFound
      end
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def article_status(article)
    case article.status
    when "public" then
      content_tag :span, "公開", :class => "label label-success"
    when "member_only" then
      content_tag :span, "会員限定", :class => "label label-info"
    when "draft" then
      content_tag :span, "下書き", :class => "label label-warning"
    else
      nil
    end
  end
end

app/views/articles/_commented.html.erb
<% @articles = @user.commented_articles.published.order("comments.created_at DESC") if @user %>
<% if @articles.present? %>
<div class="panel panel-default">
  <ul class="list-group">
  	<% @articles.each do |article| %>
    <li class="list-group-item">
		<div class="media">
		  <%= user_image_tag article.author, class: "pull-left img-circle article-list-icon", height: 64, title: article.author.full_name %>
		  <div class="media-body">
		    <div class="media-heading">
		    	<%= article_status(article) %>
		    	<h4><%= link_to article.title, article_path(article) %></h4>
		    </div>
		   	by <%= link_to article.author.full_name, user_path(article.author) %>
		  	<span style="float:right">
			  	<%=l article.released_at %>	  	
			  	<% if article.votes.count > 0 %>
			  	<span class="label label-primary">★<%= article.votes.count %></span>
			  	<% end %>
		  	</span>
		  </div>
		</div>
    </li>
    <% end %>
  </ul>
</div>
<% else %>
<p class="contents-block">コメントがまだありません。</p>
<% end %>

app/views/articles/_form.html.erb
<%= simple_form_for @article, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :title %>
  <%= error_span(@article[:title]) %>
  <%= f.input :description, :input_html => { :rows => 20 } %>
  <%= error_span(@article[:description]) %>
  <%= f.input :released_at %>
  <%= error_span(@article[:released_at]) %>
  <%= f.input :status, as: :radio_buttons, collection: [["下書き", "draft"], ["会員限定", "member_only"], ["公開", "public"]] %>
  <%= error_span(@article[:status]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                articles_path, :class => 'btn btn-default' %>
<% end %>

app/views/articles/_list.html.erb
<% if @articles.present? %>
<div class="panel panel-default">
	<% if controller.controller_name == "top" %>
  <div class="panel-heading">最新の記事一覧</div>
  <% end %>
  <ul class="list-group">
  	<% @articles.each do |article| %>
    <li class="list-group-item">
		<div class="media">
		  <%= user_image_tag article.author, class: "pull-left img-circle article-list-icon", height: 64, title: article.author.full_name %>
		  <div class="media-body">
		    <div class="media-heading">
		    	<%= article_status(article) %>
		    	<h4><%= link_to article.title, article_path(article) %></h4>
		    </div>
		   	by <%= link_to article.author.full_name, user_path(article.author) %>
		   	<span style="float:right">
			  	<%=l article.released_at %>	  	
			  	<% if article.votes.count > 0 %>
			  	<span class="label label-primary">★<%= article.votes.count %></span>
			  	<% end %>
		  	</span>
		  </div>
		</div>
    </li>
    <% end %>
  </ul>
</div>
<%= paginate @articles %>
<% else %>
<p class="contents-block">記事がまだありません。</p>
<% end %>

app/views/articles/_voted.html.erb
<% @articles = @user.voted_articles.published.order("votes.created_at DESC") if @user %>
<% if @articles.present? %>
<div class="panel panel-default">
  <ul class="list-group">
  	<% @articles.each do |article| %>
    <li class="list-group-item">
		<div class="media">
		  <%= user_image_tag article.author, class: "pull-left img-circle article-list-icon", height: 64, title: article.author.full_name %>
		  <div class="media-body">
		    <div class="media-heading">
		    	<%= article_status(article) %>
		    	<h4><%= link_to article.title, article_path(article) %></h4>
		    </div>
		   	by <%= link_to article.author.full_name, user_path(article.author) %>
		  	<span style="float:right">
		  		<%=l article.released_at %>	  	
		  		<% if article.votes.count > 0 %>
		  		<span class="label label-primary">★<%= article.votes.count %></span>
		  		<% end %>
		  	</span>
		  </div>
		</div>
    </li>
    <% end %>
  </ul>
</div>
<% else %>
<p class="contents-block">投票がまだありません。</p>
<% end %>

app/views/articles/commented.html.erb
<%- model_class = Article -%>
<div class="page-header">
	<% @page_title = "コメントした記事一覧" %>
  <h1><%= @page_title %></h1>
</div>

<%= render "commented" %>

app/views/articles/edit.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Article.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/articles/index.html.erb
<div class="page-header">
	<% @page_title = @user ? @user.full_name + "さんの投稿記事一覧" : "記事一覧" %>
  <h1><%= @page_title %></h1>
</div>

<% @articles.each do |article| %>
<div class="panel panel-default">
  <div class="panel-heading">
    <h2 class="panel-title">
    	<%= article_status(article) %>
    	<%= link_to article.title, article_path(article) %>
    </h2>
  </div>
  <div class="panel-body">
    <%= markdown truncate(article.description, length: 100) %>
    <span style="float: right;"><%= link_to "もっと読む", article %></span>
  </div>
  <div class="panel-footer">
  	<%= user_image_tag article.author, class: "img-circle", height: 32 %>
  	<%= link_to article.author.full_name, user_path(article.author) %>
  	
  	<span style="float: right;">
  	<%=l article.released_at %>
  	<% if article.votes.count > 0 %>
  	<span class="label label-primary">★<%= article.votes.count %></span>
  	<% end %>
  	</span>
  	 
  	<% if current_user %>
  	<%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_article_path(article), :class => 'btn btn-default btn-xs' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                article_path(article),
                :method => :delete,
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-xs btn-danger' %>
    <% end %>
 	</div>
</div>
<% end %>

<%= paginate @articles %>

<% if current_user %>
<p>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_article_path,
            :class => 'btn btn-primary' %>
</p>
<% end %>

app/views/articles/new.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Article.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/articles/show.html.erb
<%- model_class = Article -%>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
    	<%= article_status(@article) %>
    	<%= @article.title %>
    </h3>
  </div>
  <div class="panel-body">
    <%= markdown @article.description %>
  </div>
  <div class="panel-footer">
  	by <%= user_image_tag @article.author, class: "img-circle", height: 32, title: @article.author.full_name %>
  	<%= link_to @article.author.full_name, user_path(@article.author) %>
  	
  	<span style="float:right"><%=l @article.released_at %></span>
  	<p>
  	<p>
  		この記事に<%= @article.votes.count %>人がいいね！しています。
  		<% if current_user && current_user.votable_for?(@article) %>
	  		<%= link_to "★いいね！", [:like, @article], method: :patch, class: "btn btn-primary btn-xs" %>
	  	<% elsif current_user && @article.author.id != session[:user_id] %>
	  		<%= link_to "★取消", [:unlike, @article], method: :patch, data: { confirm: "取り消しますか？" }, class: "btn btn-danger btn-xs" %>
	  	<% end %>
  	</p>
  	<% @article.voters.order("votes.created_at").each do |voter| %>
  		<%= user_image_tag voter, class: "img-circle", height: 32, title: voter.full_name %>
  	<% end %>
  	</p>
 	</div>
</div>

<%= link_to t('.back', :default => t("helpers.links.back")),
              articles_path, :class => 'btn btn-default'  %>
<% if current_user %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_article_path(@article), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              article_path(@article),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
<% end %>

<% if current_user && @article.status != "draft" %>
<div class="well content-block-top">
  <%= form_tag({ controller: "articles", id: @article.id, action: "comment" }, :method => :patch) do %>
    <%= text_area_tag(:comment, "", { class: "form-control", rows: 5 }) %>
    <%= error_span(@article[:comment]) %>
    <%= submit_tag("コメントする", { class: "btn btn-default btn-primary content-block-top" }) %>
  <% end %>
</div>
<% end %>

<div class="panel panel-default content-block-top">
  <div class="panel-heading">コメント一覧</div>
  <% if @comments.present? %>
  <ul class="list-group">
  	<% @comments.each do |comment| %>
    <li class="list-group-item">
		<div class="media">
		  <%= comment_user_image comment, class: "pull-left img-circle article-list-icon", height: 64, title: comment.full_name %>
		  <div class="media-body">
				<%= markdown comment.comment %>
		   	by <%= link_to comment.full_name, user_path(comment.user_id) %>
		  	<span style="float:right">
		  		<%=l comment.created_at %>	  
		  	</span>	
		  </div>
		</div>
    </li>
    <% end %>
  </ul>
  <% else %>
  <p class="comment-block">コメントはまだありません。</p>
  <% end %>
</div>

app/views/articles/voted.html.erb
<%- model_class = Article -%>
<div class="page-header">
	<% @page_title = "投票した記事一覧" %>
  <h1><%= @page_title %></h1>
</div>

<%= render "voted" %>