config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
  get 'top/index'
  end

  root "top#index"
  
  get "about" => "top#about", as: "about"
  get "login" => "top#login", as: "login"

  resources :users, only: [:index, :show] do
    resources :articles, only: [:index]
  end
  resources :articles do
    member { patch :like, :unlike, :comment }
    collection { get :voted, :commented }
    resources :comments
  end
  resource :session, only: [:create, :destroy]
  resource :account, only: [:show, :edit, :update]
  
  namespace :admin do
    root to: "top#index"
    resources :users
  end

end

app/views/shared/_errors.html.erb
<% if obj.errors.present? %>
<div id="errors">
<h3>エラーがあります。</h3>
<ul>
  <% obj.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
  <% end %>
</ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<p class="footer-block">
<%= link_to "このサイトについて", about_path %> |
Created by <%= link_to "yusukixs", "https://github.com/yusukixs/yiiter" %>
2015
</p>

app/views/shared/_header.html.erb
<% if current_user && current_user.administrator? %>
<div class="navbar navbar-inverse navbar-static-top">
<% else %>
<div class="navbar navbar-default navbar-static-top">
<% end %>
	<div class="container">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" style="padding: 0;" href="/"><%= image_tag("logo.png", size: "135x50", alt: "Yiiter") %></a>
		<div class="navbar-collapse collapse navbar-responsive-collapse">
			<ul class="nav navbar-nav">
				<li>
					<%= link_to "HOME", :root %>
				</li>
				<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">記事<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "記事一覧", :articles  %></li>
            <% if current_user %>
            <li><%= link_to "記事を作成する", :new_article %></li>
            <li><%= link_to "投票した記事", :voted_articles %></li>
            <% else %>
            <li class="disabled"><%= link_to "記事を作成する", "#" %></li>
            <li class="disabled"><%= link_to "投票した記事", "#" %></li>
            <% end %>
          </ul>
        </li>
				<% if current_user && current_user.administrator? %>
				<li>
					<%= link_to "ユーザー管理", :admin_users %>
				</li>
				<% end %>
			</ul>
			<p class="navbar-text navbar-right btn-login-header">
			<% if current_user %>
				<%= user_image_tag current_user, class: "img-circle", height: 32 %>
				<%= link_to current_user.full_name + "さん", user_path(current_user) %> |
				<%= link_to "ログアウト", :session,
				      method: :delete, data: { confirm: "ログアウトしますか？" } %>
			<% else %>
				<%= link_to "ログイン", login_path, class:"btn btn-info btn-sm" %>
			<% end %>
			</p>
		</div>
	</div>
</div>

app/views/shared/_login_form.html.erb
<h2>ログイン</h2>

<%= form_tag :session do %>
<table id="login_form">
  <tr>
    <td style="text-align: right">ユーザー名：</td>
    <td><%= text_field_tag "account_name", "", style: "width: 120px" %></td>
  </tr>
  <tr>
    <td style="text-align: right">パスワード：</td>
    <td><%= password_field_tag "password", "", style: "width: 120px" %></td>
  </tr>
  <tr>
    <td colspan="2" style="text-align: center">
    <%= submit_tag "ログイン" %></td>
  </tr>
</table>
<% end %>

app/views/shared/_sidebar.html.erb
<div class="well sidebar-nav">
<% if current_user %>
<p>
	<%= link_to "記事を作成する", :new_article %>
</p>
<p>
	<%= link_to "投票した記事", :voted_articles %>
</p>
<p>
	<%= link_to "コメントした記事", :commented_articles %>
</p>
<% end %>

<h2>最新記事</h2>
<ul>
	<% Article.sidebar_articles(current_user, 5).each do |article| %>
	<li>
		<%= link_to article.title, article %>
		<%- model_class = Article -%>
		by <%= link_to article.author.full_name, user_path(article.author) %>
  	<p><%=l article.released_at %></p>
	</li>
	<% end %>
</ul>
</div>